backend:
  name: github
  repo: hafid-eng/coffesite  # استبدل بالاسم الصحيح
  branch: main  # تأكد من أن هذا هو اسم الفرع الصحيح في GitHub

media_folder: "images/uploads"  # مجلد الوسائط داخل الريبو (يمكن تعديله حسب حاجتك)
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"  # المسار حيث سيتم حفظ الملفات
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
